version: "3.8"

services:
  backend:
    container_name: parking-lot-api
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - .env
    ports:
      - "3000:3000"
